export const AUCTION_LIST_REQUEST = 'AUCTION_LIST_REQUEST'
export const AUCTION_LIST_SUCCESS = 'AUCTION_LIST_SUCCESS'
export const AUCTION_LIST_FAIL = 'AUCTION_LIST_FAIL'

export const AUCTION_S_LIST_REQUEST = 'AUCTION_S_LIST_REQUEST'
export const AUCTION_S_LIST_SUCCESS = 'AUCTION_S_LIST_SUCCESS'
export const AUCTION_S_LIST_FAIL = 'AUCTION_S_LIST_FAIL'

export const AUCTION_DETAILS_REQUEST = 'AUCTION_DETAILS_REQUEST'
export const AUCTION_DETAILS_SUCCESS = 'AUCTION_DETAILS_SUCCESS'
export const AUCTION_DETAILS_FAIL = 'AUCTION_DETAILS_FAIL'

export const AUCTION_DELETE_REQUEST = 'AUCTION_DELETE_REQUEST'
export const AUCTION_DELETE_SUCCESS = 'AUCTION_DELETE_SUCCESS'
export const AUCTION_DELETE_FAIL = 'AUCTION_DELETE_FAIL'

export const AUCTION_CREATE_REQUEST = 'AUCTION_CREATE_REQUEST'
export const AUCTION_CREATE_SUCCESS = 'AUCTION_CREATE_SUCCESS'
export const AUCTION_CREATE_FAIL = 'AUCTION_CREATE_FAIL'
export const AUCTION_CREATE_RESET = 'AUCTION_CREATE_RESET'

export const AUCTION_UPDATE_REQUEST = 'AUCTION_UPDATE_REQUEST'
export const AUCTION_UPDATE_SUCCESS = 'AUCTION_UPDATE_SUCCESS'
export const AUCTION_UPDATE_FAIL = 'AUCTION_UPDATE_FAIL'
export const AUCTION_UPDATE_RESET = 'AUCTION_UPDATE_RESET'

export const AUCTION_CREATE_REVIEW_REQUEST = 'AUCTION_CREATE_REVIEW_REQUEST'
export const AUCTION_CREATE_REVIEW_SUCCESS = 'AUCTION_CREATE_REVIEW_SUCCESS'
export const AUCTION_CREATE_REVIEW_FAIL = 'AUCTION_CREATE_REVIEW_FAIL'
export const AUCTION_CREATE_REVIEW_RESET = 'AUCTION_CREATE_REVIEW_RESET'

export const AUCTION_TOP_REQUEST = 'AUCTION_TOP_REQUEST'
export const AUCTION_TOP_SUCCESS = 'AUCTION_TOP_SUCCESS'
export const AUCTION_TOP_FAIL = 'AUCTION_TOP_FAIL'
export const AUCTION_TOP_RESET = 'AUCTION_TOP_RESET'

export const AUCTION_LIST_MY_REQUEST = 'AUCTION_LIST_MY_REQUEST'
export const AUCTION_LIST_MY_SUCCESS = 'AUCTION_LIST_MY_SUCCESS'
export const AUCTION_LIST_MY_FAIL = 'AUCTION_LIST_MY_FAIL'
export const AUCTION_LIST_MY_RESET = 'AUCTION_LIST_MY_RESET'