export const BID_LIST_REQUEST = 'BID_LIST_REQUEST'
export const BID_LIST_SUCCESS = 'BID_LIST_SUCCESS'
export const BID_LIST_FAIL = 'BID_LIST_FAIL'

export const BID_S_LIST_REQUEST = 'BID_S_LIST_REQUEST'
export const BID_S_LIST_SUCCESS = 'BID_S_LIST_SUCCESS'
export const BID_S_LIST_FAIL = 'BID_S_LIST_FAIL'

export const BID_DETAILS_REQUEST = 'BID_DETAILS_REQUEST'
export const BID_DETAILS_SUCCESS = 'BID_DETAILS_SUCCESS'
export const BID_DETAILS_FAIL = 'BID_DETAILS_FAIL'

export const BID_DELETE_REQUEST = 'BID_DELETE_REQUEST'
export const BID_DELETE_SUCCESS = 'BID_DELETE_SUCCESS'
export const BID_DELETE_FAIL = 'BID_DELETE_FAIL'

export const BID_CREATE_REQUEST = 'BID_CREATE_REQUEST'
export const BID_CREATE_SUCCESS = 'BID_CREATE_SUCCESS'
export const BID_CREATE_FAIL = 'BID_CREATE_FAIL'
export const BID_CREATE_RESET = 'BID_CREATE_RESET'

export const BID_UPDATE_REQUEST = 'BID_UPDATE_REQUEST'
export const BID_UPDATE_SUCCESS = 'BID_UPDATE_SUCCESS'
export const BID_UPDATE_FAIL = 'BID_UPDATE_FAIL'
export const BID_UPDATE_RESET = 'BID_UPDATE_RESET'

export const BID_CREATE_REVIEW_REQUEST = 'BID_CREATE_REVIEW_REQUEST'
export const BID_CREATE_REVIEW_SUCCESS = 'BID_CREATE_REVIEW_SUCCESS'
export const BID_CREATE_REVIEW_FAIL = 'BID_CREATE_REVIEW_FAIL'
export const BID_CREATE_REVIEW_RESET = 'BID_CREATE_REVIEW_RESET'

export const BID_TOP_REQUEST = 'BID_TOP_REQUEST'
export const BID_TOP_SUCCESS = 'BID_TOP_SUCCESS'
export const BID_TOP_FAIL = 'BID_TOP_FAIL'
export const BID_TOP_RESET = 'BID_TOP_RESET'

export const BID_LIST_MY_REQUEST = 'BID_LIST_MY_REQUEST'
export const BID_LIST_MY_SUCCESS = 'BID_LIST_MY_SUCCESS'
export const BID_LIST_MY_FAIL = 'BID_LIST_MY_FAIL'
export const BID_LIST_MY_RESET = 'BID_LIST_MY_RESET'

export const BID_LIST_M_REQUEST = 'BID_LIST_M_REQUEST'
export const BID_LIST_M_SUCCESS = 'BID_LIST_M_SUCCESS'
export const BID_LIST_M_FAIL = 'BID_LIST_M_FAIL'
export const BID_LIST_M_RESET = 'BID_LIST_M_RESET'