export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS'
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL'

export const BOOK_S_LIST_REQUEST = 'BOOK_S_LIST_REQUEST'
export const BOOK_S_LIST_SUCCESS = 'BOOK_S_LIST_SUCCESS'
export const BOOK_S_LIST_FAIL = 'BOOK_S_LIST_FAIL'

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST'
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS'
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL'

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST'
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS'
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL'

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST'
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS'
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL'
export const BOOK_CREATE_RESET = 'BOOK_CREATE_RESET'

export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST'
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS'
export const BOOK_UPDATE_FAIL = 'BOOK_UPDATE_FAIL'
export const BOOK_UPDATE_RESET = 'BOOK_UPDATE_RESET'

export const BOOK_CREATE_REVIEW_REQUEST = 'BOOK_CREATE_REVIEW_REQUEST'
export const BOOK_CREATE_REVIEW_SUCCESS = 'BOOK_CREATE_REVIEW_SUCCESS'
export const BOOK_CREATE_REVIEW_FAIL = 'BOOK_CREATE_REVIEW_FAIL'
export const BOOK_CREATE_REVIEW_RESET = 'BOOK_CREATE_REVIEW_RESET'

export const BOOK_TOP_REQUEST = 'BOOK_TOP_REQUEST'
export const BOOK_TOP_SUCCESS = 'BOOK_TOP_SUCCESS'
export const BOOK_TOP_FAIL = 'BOOK_TOP_FAIL'
export const BOOK_TOP_RESET = 'BOOK_TOP_RESET'

export const BOOK_LIST_MY_REQUEST = 'BOOK_LIST_MY_REQUEST'
export const BOOK_LIST_MY_SUCCESS = 'BOOK_LIST_MY_SUCCESS'
export const BOOK_LIST_MY_FAIL = 'BOOK_LIST_MY_FAIL'
export const BOOK_LIST_MY_RESET = 'BOOK_LIST_MY_RESET'

export const BOOK_LIST_M_REQUEST = 'BOOK_LIST_M_REQUEST'
export const BOOK_LIST_M_SUCCESS = 'BOOK_LIST_M_SUCCESS'
export const BOOK_LIST_M_FAIL = 'BOOK_LIST_M_FAIL'
export const BOOK_LIST_M_RESET = 'BOOK_LIST_M_RESET'