export const EMAIL_REGISTER_REQUEST = 'EMAIL_REGISTER_REQUEST'
export const EMAIL_REGISTER_SUCCESS = 'EMAIL_REGISTER_SUCCESS'
export const EMAIL_REGISTER_FAIL = 'EMAIL_REGISTER_FAIL'

export const EMAIL_LIST_REQUEST = 'EMAIL_LIST_REQUEST'
export const EMAIL_LIST_SUCCESS = 'EMAIL_LIST_SUCCESS'
export const EMAIL_LIST_FAIL = 'EMAIL_LIST_FAIL'