export const MANAGER_LOGIN_REQUEST = 'MANAGER_LOGIN_REQUEST'
export const MANAGER_LOGIN_SUCCESS = 'MANAGER_LOGIN_SUCCESS'
export const MANAGER_LOGIN_FAIL = 'MANAGER_LOGIN_FAIL'
export const MANAGER_LOGOUT = 'MANAGER_LOGOUT'

export const MANAGER_REGISTER_REQUEST = 'MANAGER_REGISTER_REQUEST'
export const MANAGER_REGISTER_SUCCESS = 'MANAGER_REGISTER_SUCCESS'
export const MANAGER_REGISTER_FAIL = 'MANAGER_REGISTER_FAIL'

export const MANAGER_DETAILS_REQUEST = 'MANAGER_DETAILS_REQUEST'
export const MANAGER_DETAILS_SUCCESS = 'MANAGER_DETAILS_SUCCESS'
export const MANAGER_DETAILS_FAIL = 'MANAGER_DETAILS_FAIL'
export const MANAGER_DETAILS_RESET = 'MANAGER_DETAILS_RESET'

export const MANAGER_LIST_REQUEST = 'MANAGER_LIST_REQUEST'
export const MANAGER_LIST_SUCCESS = 'MANAGER_LIST_SUCCESS'
export const MANAGER_LIST_FAIL = 'MANAGER_LIST_FAIL'
export const MANAGER_LIST_RESET = 'MANAGER_LIST_RESET'

export const MANAGER_DELETE_REQUEST = 'MANAGER_DELETE_REQUEST'
export const MANAGER_DELETE_SUCCESS = 'MANAGER_DELETE_SUCCESS'
export const MANAGER_DELETE_FAIL = 'MANAGER_DELETE_FAIL'

export const MANAGER_UPDATE_PROFILE_REQUEST = 'MANAGER_UPDATE_PROFILE_REQUEST'
export const MANAGER_UPDATE_PROFILE_SUCCESS = 'MANAGER_UPDATE_PROFILE_SUCCESS'
export const MANAGER_UPDATE_PROFILE_FAIL = 'MANAGER_UPDATE_PROFILE_FAIL'
export const MANAGER_UPDATE_PROFILE_RESET = 'MANAGER_UPDATE_PROFILE_RESET'

export const MANAGER_UPDATE_REQUEST = 'MANAGER_UPDATE_REQUEST'
export const MANAGER_UPDATE_SUCCESS = 'MANAGER_UPDATE_SUCCESS'
export const MANAGER_UPDATE_FAIL = 'MANAGER_UPDATE_FAIL'
export const MANAGER_UPDATE_RESET = 'MANAGER_UPDATE_RESET'