export const MECHANIC_LOGIN_REQUEST = 'MECHANIC_LOGIN_REQUEST'
export const MECHANIC_LOGIN_SUCCESS = 'MECHANIC_LOGIN_SUCCESS'
export const MECHANIC_LOGIN_FAIL = 'MECHANIC_LOGIN_FAIL'
export const MECHANIC_LOGOUT = 'MECHANIC_LOGOUT'

export const MECHANIC_REGISTER_REQUEST = 'MECHANIC_REGISTER_REQUEST'
export const MECHANIC_REGISTER_SUCCESS = 'MECHANIC_REGISTER_SUCCESS'
export const MECHANIC_REGISTER_FAIL = 'MECHANIC_REGISTER_FAIL'

export const MECHANIC_DETAILS_REQUEST = 'MECHANIC_DETAILS_REQUEST'
export const MECHANIC_DETAILS_SUCCESS = 'MECHANIC_DETAILS_SUCCESS'
export const MECHANIC_DETAILS_FAIL = 'MECHANIC_DETAILS_FAIL'
export const MECHANIC_DETAILS_RESET = 'MECHANIC_DETAILS_RESET'

export const MECHANIC_LIST_REQUEST = 'MECHANIC_LIST_REQUEST'
export const MECHANIC_LIST_SUCCESS = 'MECHANIC_LIST_SUCCESS'
export const MECHANIC_LIST_FAIL = 'MECHANIC_LIST_FAIL'
export const MECHANIC_LIST_RESET = 'MECHANIC_LIST_RESET'

export const MECHANIC_DELETE_REQUEST = 'MECHANIC_DELETE_REQUEST'
export const MECHANIC_DELETE_SUCCESS = 'MECHANIC_DELETE_SUCCESS'
export const MECHANIC_DELETE_FAIL = 'MECHANIC_DELETE_FAIL'

export const MECHANIC_UPDATE_PROFILE_REQUEST = 'MECHANIC_UPDATE_PROFILE_REQUEST'
export const MECHANIC_UPDATE_PROFILE_SUCCESS = 'MECHANIC_UPDATE_PROFILE_SUCCESS'
export const MECHANIC_UPDATE_PROFILE_FAIL = 'MECHANIC_UPDATE_PROFILE_FAIL'
export const MECHANIC_UPDATE_PROFILE_RESET = 'MECHANIC_UPDATE_PROFILE_RESET'

export const MECHANIC_UPDATE_REQUEST = 'MECHANIC_UPDATE_REQUEST'
export const MECHANIC_UPDATE_SUCCESS = 'MECHANIC_UPDATE_SUCCESS'
export const MECHANIC_UPDATE_FAIL = 'MECHANIC_UPDATE_FAIL'
export const MECHANIC_UPDATE_RESET = 'MECHANIC_UPDATE_RESET'

export const MECHANIC_S_LIST_REQUEST = 'MECHANIC_S_LIST_REQUEST'
export const MECHANIC_S_LIST_SUCCESS = 'MECHANIC_S_LIST_SUCCESS'
export const MECHANIC_S_LIST_FAIL = 'MECHANIC_S_LIST_FAIL'

export const MECHANIC_CREATE_REQUEST = 'MECHANIC_CREATE_REQUEST'
export const MECHANIC_CREATE_SUCCESS = 'MECHANIC_CREATE_SUCCESS'
export const MECHANIC_CREATE_FAIL = 'MECHANIC_CREATE_FAIL'
export const MECHANIC_CREATE_RESET = 'MECHANIC_CREATE_RESET'


export const MECHANIC_CREATE_REVIEW_REQUEST = 'MECHANIC_CREATE_REVIEW_REQUEST'
export const MECHANIC_CREATE_REVIEW_SUCCESS = 'MECHANIC_CREATE_REVIEW_SUCCESS'
export const MECHANIC_CREATE_REVIEW_FAIL = 'MECHANIC_CREATE_REVIEW_FAIL'
export const MECHANIC_CREATE_REVIEW_RESET = 'MECHANIC_CREATE_REVIEW_RESET'

export const MECHANIC_TOP_REQUEST = 'MECHANIC_TOP_REQUEST'
export const MECHANIC_TOP_SUCCESS = 'MECHANIC_TOP_SUCCESS'
export const MECHANIC_TOP_FAIL = 'MECHANIC_TOP_FAIL'
export const MECHANIC_TOP_RESET = 'MECHANIC_TOP_RESET'
