export const PROT_LIST_REQUEST = 'PROT_LIST_REQUEST'
export const PROT_LIST_SUCCESS = 'PROT_LIST_SUCCESS'
export const PROT_LIST_FAIL = 'PROT_LIST_FAIL'

export const PROT_S_LIST_REQUEST = 'PROT_S_LIST_REQUEST'
export const PROT_S_LIST_SUCCESS = 'PROT_S_LIST_SUCCESS'
export const PROT_S_LIST_FAIL = 'PROT_S_LIST_FAIL'

export const PROT_DETAILS_REQUEST = 'PROT_DETAILS_REQUEST'
export const PROT_DETAILS_SUCCESS = 'PROT_DETAILS_SUCCESS'
export const PROT_DETAILS_FAIL = 'PROT_DETAILS_FAIL'

export const PROT_DELETE_REQUEST = 'PROT_DELETE_REQUEST'
export const PROT_DELETE_SUCCESS = 'PROT_DELETE_SUCCESS'
export const PROT_DELETE_FAIL = 'PROT_DELETE_FAIL'

export const PROT_CREATE_REQUEST = 'PROT_CREATE_REQUEST'
export const PROT_CREATE_SUCCESS = 'PROT_CREATE_SUCCESS'
export const PROT_CREATE_FAIL = 'PROT_CREATE_FAIL'
export const PROT_CREATE_RESET = 'PROT_CREATE_RESET'

export const PROT_UPDATE_REQUEST = 'PROT_UPDATE_REQUEST'
export const PROT_UPDATE_SUCCESS = 'PROT_UPDATE_SUCCESS'
export const PROT_UPDATE_FAIL = 'PROT_UPDATE_FAIL'
export const PROT_UPDATE_RESET = 'PROT_UPDATE_RESET'

export const PROT_CREATE_REVIEW_REQUEST = 'PROT_CREATE_REVIEW_REQUEST'
export const PROT_CREATE_REVIEW_SUCCESS = 'PROT_CREATE_REVIEW_SUCCESS'
export const PROT_CREATE_REVIEW_FAIL = 'PROT_CREATE_REVIEW_FAIL'
export const PROT_CREATE_REVIEW_RESET = 'PROT_CREATE_REVIEW_RESET'

export const PROT_TOP_REQUEST = 'PROT_TOP_REQUEST'
export const PROT_TOP_SUCCESS = 'PROT_TOP_SUCCESS'
export const PROT_TOP_FAIL = 'PROT_TOP_FAIL'
export const PROT_TOP_RESET = 'PROT_TOP_RESET'

export const PROT_LIST_MY_REQUEST = 'PROT_LIST_MY_REQUEST'
export const PROT_LIST_MY_SUCCESS = 'PROT_LIST_MY_SUCCESS'
export const PROT_LIST_MY_FAIL = 'PROT_LIST_MY_FAIL'
export const PROT_LIST_MY_RESET = 'PROT_LIST_MY_RESET'