export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST'
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS'
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL'

export const STORE_DETAILS_REQUEST = 'STORE_DETAILS_REQUEST'
export const STORE_DETAILS_SUCCESS = 'STORE_DETAILS_SUCCESS'
export const STORE_DETAILS_FAIL = 'STORE_DETAILS_FAIL'

export const STORE_DELETE_REQUEST = 'STORE_DELETE_REQUEST'
export const STORE_DELETE_SUCCESS = 'STORE_DELETE_SUCCESS'
export const STORE_DELETE_FAIL = 'STORE_DELETE_FAIL'

export const STORE_CREATE_REQUEST = 'STORE_CREATE_REQUEST'
export const STORE_CREATE_SUCCESS = 'STORE_CREATE_SUCCESS'
export const STORE_CREATE_FAIL = 'STORE_CREATE_FAIL'
export const STORE_CREATE_RESET = 'STORE_CREATE_RESET'

export const STORE_UPDATE_REQUEST = 'STORE_UPDATE_REQUEST'
export const STORE_UPDATE_SUCCESS = 'STORE_UPDATE_SUCCESS'
export const STORE_UPDATE_FAIL = 'STORE_UPDATE_FAIL'
export const STORE_UPDATE_RESET = 'STORE_UPDATE_RESET'

export const STORE_CREATE_REVIEW_REQUEST = 'STORE_CREATE_REVIEW_REQUEST'
export const STORE_CREATE_REVIEW_SUCCESS = 'STORE_CREATE_REVIEW_SUCCESS'
export const STORE_CREATE_REVIEW_FAIL = 'STORE_CREATE_REVIEW_FAIL'
export const STORE_CREATE_REVIEW_RESET = 'STORE_CREATE_REVIEW_RESET'

export const STORE_TOP_REQUEST = 'STORE_TOP_REQUEST'
export const STORE_TOP_SUCCESS = 'STORE_TOP_SUCCESS'
export const STORE_TOP_FAIL = 'STORE_TOP_FAIL'
export const STORE_TOP_RESET = 'STORE_TOP_RESET'

export const STORE_LIST_MY_REQUEST = 'STORE_LIST_MY_REQUEST'
export const STORE_LIST_MY_SUCCESS = 'STORE_LIST_MY_SUCCESS'
export const STORE_LIST_MY_FAIL = 'STORE_LIST_MY_FAIL'
export const STORE_LIST_MY_RESET = 'STORE_LIST_MY_RESET'